general:
  # The distance in blocks to search for blocks while parsing a location
  block-search-radius: 10
  # The distance in blocks to search for carts while setting or querying codes
  cart-search-distance: 10
  # Are webhooks enabled in the plugin?
  webhooks-enabled: false

webhooks:
  # Definition of a webhook that is called when a cart moved
  cart-moved:
    type: [CART_MOVED]
    url: "https://www.example.com/webhook/cart_moved"
  # Definition of a webhook that is called when a player enters a cart
  player-entered-cart:
    type: [CART_ENTERED]
    url: "https://www.example.com/webhook/cart_entered"

cart-prompt:
  # The title to use in the /gcart prompt command
  title: "Select a code"
  # The material to use for items in the /gcart prompt command
  item-material: MINECART
  # The distance in blocks to search for a player to display the prompt to
  player-search-radius: 5

butcher:
  # Should mobs within the specified radius of a player riding a minecart be killed?
  enabled: true
  # The radius in blocks in which mobs will be killed
  radius: 5
  # Should a lightning bolt effect be used when a mob is killed?
  lightning-bolt-effect: true
  # The entity types to ignore besides players
  ignore-entities-of-type: [ALLAY, VILLAGER]
  # Should entities bearing a custom name be ignored?
  ignore-named-entities: true
  # Should item drops of killed entities be disabled?
  disable-item-drops: true

messages:
  # General messages
  plugin-reloaded: "<name> has been reloaded"
  location-format: "<blue><click:copy_to_clipboard:'<location>'><hover:show_text:'Click to copy \"<location>\" to clipboard'><location></hover></click></blue>"
  block-format: "block <material> at <location>"
  cart-format: "minecart with code <code> at <location>"
  no-block-found: "<red>No block found</red>"
  no-cart-found: "<red>No cart found</red>"

  # Messages for the /gtag command
  tag-list: "<count> code tags are defined"
  tag-list-item: "- <code> <link:''>"
  tag-name-changed: "The name of code tag <green><code></green> has been changed to <name>"
  tag-url-changed: "The URL of code tag <green><code></green> has been changed to <url>"
  tag-name-cleared: "The name of code tag <green><code></green> has been cleared"
  tag-url-cleared: "The URL of code tag <green><code></green> has been cleared"
  tag-removed: "The code tag <green><code></green> has been removed"

  # Messages for the /gcart command
  cart-code-changed: "The code of <cart> was changed from <green><original-code></green> to <green><code></green>"
  cart-code-cleared: "The code of <cart> was cleared from <green><original-code></green>"
  cart-code-retained: "The code of <cart> was unchanged from <green><original-code></green>"
  cart-code-speed-multiplier-changed: "The speed multiplier of <cart> was changed from <green><original-speed-multiplier:'#.0'> to <green><speed-multiplier:'#.0'></green>"
  cart-code-speed-multiplier-retained: "The speed multiplier of <cart> was unchanged from <green><original-speed-multiplier:'#.0'></green>"

  # Messages for the /grail command
  block-shape-changed: "The shape of <block> was changed from <green><original-shape></green> to <green><shape></green>"
  block-shape-retained: "The shape of <block> was unchanged from <green><original-shape></green>"
  block-material-changed: "The material of <block> was changed from <green><original-material> to <green><material></green>"
  block-material-retained: "The material of <block> was unchanged from <green><original-material></green>"
  sound-played: "Sound <sound> was played at <location>"
