general:
  # The distance in blocks to search for blocks while parsing a location
  block-search-radius: 10
  # The distance in blocks to search for carts while setting or querying codes
  cart-search-distance: 10
  # Are webhooks enabled in the plugin?
  webhooks-enabled: true
  
webhooks:
  # Definition of a webhook that is called when a cart moved
  cart-moved:
    type: [CART_MOVED]
    url: "https://www.example.com/webhook/cart_moved"
  # Definition of a webhook that is called when a player enters a cart
  player-entered-cart:
    type: [CART_ENTERED]
    url: "https://www.example.com/webhook/cart_entered"
  
cart-prompt:
  # The title to use in the /gcart prompt command
  title: "Select a code"
  # The material to use for items in the /gcart prompt command
  item-material: MINECART
  # The distance in blocks to search for a player to display the prompt to
  player-search-radius: 5
  
butcher:
  # Should mobs within the specified radius of a player riding a minecart be killed?
  enabled: true
  # The radius in blocks in which mobs will be killed
  radius: 5
  # Should a lightning bolt effect be used when a mob is killed?
  lightning-bolt-effect: true
  # The entity types to ignore besides players
  ignore-entities-of-type: [ALLAY, VILLAGER]
  # Should entities bearing a custom name be ignored?
  ignore-named-entities: true
  # Should item drops of killed entities be disabled?
  disable-item-drops: true