name: GregoRail
description: Powerful railroad management tools for Minecraft.
version: 2.0.0
author: danae
website: https://github.com/danae/gregorail
main: dev.danae.gregorail.plugin.GregoRailPlugin
api-version: 1.20


commands:
  gregorail:
    description: Executes various administration commands.
    permission: gregorail.admin
    usage: "Usage: /<command> reload | version"

  gtag:
    description: Manages tags of minecart codes.
    usage: "Usage: /command clear <code> <property> | list | remove <code> | set <code> <property> <value>"
    
  gcart:
    description: Manages properties of minecarts.
    usage: "Usage: /<command> clear [location] | clearif <query> [location] | promptset <codes> [location] | set <code> [location] | setif <query> <code> [location] | speed <speed> [location] | speedif <code> <speed> [location]"
    
  grail:
    description: Changes the state of rails and blocks based on properties of minecarts.
    usage: "Usage: /<command> block <material> <location> | blockif <query> <material> <location> | sound <sound> | soundif <query> <sound> | switch <shape> <location> | switchif <query> <shape> <location>"
    
  glocate:
    description: Locate blocks or carts for debug purposes.
    usage: "Usage: /<command> block <location> | cart <location>"
    
    
permissions:
  gregorail.admin:
    description: Allows the player to use the /gregorail command.
    default: op

  gregorail.tag:
    description: Allows the player to use the /gtag command.
    default: op
    children:
      gregorail.cart.clear: true
      gregorail.cart.list: true
      gregorail.cart.remove: true
      gregorail.cart.set: true

  gregorail.tag.clear:
    description: Allows the player to use the /gtag clear command.
    default: op

  gregorail.tag.list:
    description: Allows the player to use the /gtag list command.
    default: op

  gregorail.tag.remove:
    description: Allows the player to use the /gtag remove command.
    default: op

  gregorail.tag.set:
    description: Allows the player to use the /gtag set command.
    default: op
    
  gregorail.cart:
    description: Allows the player to use the /gcart command.
    default: true
    children:
      gregorail.cart.clear: true
      gregorail.cart.promptset: true
      gregorail.cart.set: true
      gregorail.cart.speed: true
    
  gregorail.cart.clear:
    description: Allows the player to use the /gcart clear and clearif commands.
    default: true
      
  gregorail.cart.promptset:
    description: Allows the player to use the /gcart promptset and promptsetif commands.
    default: true
      
  gregorail.cart.set:
    description: Allows the player to use the /gcart set and setif commands.
    default: true
    
  gregorail.cart.speed:
    description: Allows the player to use the /gcart speed and speedif commands.
    default: true
    
  gregorail.rail:
    description: Allows the player to use the /grail command.
    default: true
    children:
      gregorail.rail.block: true
      gregorail.rail.sound: true
      gregorail.rail.switch: true
      
  gregorail.rail.block:
    description: Allows the player to use the /grail block and blockif commands.
    default: true
    
  gregorail.rail.sound:
    description: Allows the player to use the /grail sound and soundif commands.
    default: true
      
  gregorail.rail.switch:
    description: Allows the player to use the /grail switch and switchif commands.
    default: true
    
  gregorail.locate:
    description: Allows the player to use the /glocate command.
    default: true
    children:
      gregorail.locate.block: true
      gregorail.locate.cart: true  
      
  gregorail.locate.block:
    description: Allows the player to use the /glocate block command.
    default: true
    
  gregorail.locate.cart:
    description: Allows the player to use the /glocate cart command.
    default: true