name: GregoRail
description: Powerful railroad management tools for Minecraft.
version: 0.2.1
author: danae
main: dev.danae.gregorail.RailPlugin
api-version: 1.19

commands:
  gcart:
    description: Executes various minecart management commands.
    usage: "Usage: /<command> set <code> [location] | unset [location]"
  grail:
    description: Executes various rail management commands.
    usage: "Usage: /<command> switch <shape> <location> | switchif <code> <shape> <location>"
  gadmin:
    description: Executes various administration commands.
    usage: "Usage: /<command> locate <location> | locatecart <location>"
    
permissions:
  gregorail.cart.set:
    description: Allows the player to use the /gcart set command.
    default: true
  gregorail.cart.unset:
    description: Allows the player to use the /gcart unset command.
    default: true
  gregorail.rail.switch:
    description: Allows the player to use the /grail switch command.
    default: true
  gregorail.rail.switchif:
    description: Allows the player to use the /grail switchif command.
    default: true
  gregorail.admin.locate:
    description: Allows the player to use the /gadmin locate command.
    default: op
  gregorail.admin.locatecart:
    description: Allows the player to use the /gadmin locatecart command.
    default: op