name: GregoRail
description: Powerful railroad management tools for Minecraft.
version: 0.1.0
author: danae
main: dev.danae.gregorail.RailPlugin
api-version: 1.19

commands:
  rail:
    description: Executes various rail management commands.
    usage: "Usage: /<command> locate <location> | locatecart <location>"
    
permissions:
  gregorail.rail:
    description: Allows the player to use the /rail command.
    default: op