name: GregoRail
description: Powerful railroad management tools for Minecraft.
version: 0.1.0
author: danae
main: dev.danae.gregorail.RailPlugin
api-version: 1.19

commands:
  rail:
    description: Executes various rail management commands.
    usage: "Usage: /<command> assign <code> [location] | locate <location> | locatecart <location> | switch <shape> <location> | switchif <code> <shape> <location> | unassign [location]"
    
permissions:
  gregorail.assign:
    description: Allows the player to use the /rail assign command.
    default: true
  gregorail.locate:
    description: Allows the player to use the /rail locate command.
    default: op
  gregorail.locatecart:
    description: Allows the player to use the /rail locatecart command.
    default: op
  gregorail.switch:
    description: Allows the player to use the /rail switch command.
    default: op
  gregorail.switchif:
    description: Allows the player to use the /rail switchif command.
    default: op
  gregorail.unassign:
    description: Allows the player to use the /rail unassign command.
    default: true